theme: jekyll-theme-minimal
title: Canadian Archive of Women in STEM and Wikidata
description: Experiment to use Wikidata for the Canadian Archive of Women in STEM
logo: https://biblio.uottawa.ca/sites/biblio.uottawa.ca/files/portallogoen.jpg
show_downloads: false
